### ISSUE TITLE
Crop image is not submitted on upload ...

### ISSUE THREAD

**Issue by baki250** [LukeMason/angular-img-editor#4] opened 2014-06-02 14:07 UTC
Edited(cropped/rotated) is not submitted on upload. Instead it submits the original image path.

**Comment by LukeMason** [comment] 2014-06-03 02:44
This was the intended behavior, the original idea being that you could submit the edit metadata alongside the original files and have a backend service which manages both, serving edited versions to the public and originals capable of being re-edited to the creator. 
I can see how it would be useful for the data to be saved as presented as well so I have added the ability to persist the object's base64 encoding to a scope object, which in turn can be posted using angular's native $http post and decoded using a back end of your choosing.
README and Example are updated as well.

**Comment by baki250** [comment] 2014-06-03 14:21
This is great, Thanks.
Luke, is there a way to submit the original image too, currently the queue only allows uploaded items.
I want to store the original, just in case the user comes back and edits their profile. Also to be able to resize the current image.

Thanks for your help

**Comment by LukeMason** [comment] 2014-06-03 14:39
I wouldn't want to submit both copies of the image as well as the crop data, no need to transfer that much extra data, if you are planning on storing originals and crop information I would use the default uploader code, and have an submit method which runs something like

```
uploader.uploadAll(); 

$http.post('url',data{crops:[ { imageName: ... ,rotation: ..., crop: ...} ...]); 

```

then a back end which is saves the original, reads the crop info and generates a thumbnail / version of the image to serve up, and which is able to return the crop information for a given image by request. 
This is something I plan to code out in example 2, but I don't have too much time right now to work on it. If you want to code something up and submit a pull request I'd be happy to add other examples. 

Resizing could also happen in a thumbnail service on the back end, however it would be possible to have a 'max-size' parameter for the size of the image saved using the base64 method, submit a request for an enhancement if you have a need for that feature with a use case.

**Comment by LukeMason** [comment] 2014-06-04 20:31
Closing this, if you need any new features submit an enhancement request.

**Closed as completed by LukeMason** 2014-06-04 20:31 UTC
